/**
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-icons
 * Source: @central-icons-react
 *
 * @generated
 */

import { memo } from 'react'

import { cn } from '#lib/cn'

import { type IconProps, IconSize, iconSizeValues } from '../types'

export const IconArrowUpRight = memo(function IconArrowUpRight({
  size = IconSize.Medium,
  title,
  className,
  ref,
  ...props
}: IconProps) {
  const px = iconSizeValues[size]

  return (
    <svg
      width={px}
      height={px}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      className={cn('shrink-0', className)}
      ref={ref}
      {...props}
    >
      <path d="M18.25 15.25V5.75M18.25 5.75H8.75M18.25 5.75L6 18" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
})
