/**
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-icons
 * Source: @central-icons-react
 *
 * @generated
 */

import { memo } from 'react'

import { cn } from '#lib/cn'

import {
  IconFill,
  IconSize,
  type IconWithFillProps,
  iconSizeValues,
} from '../types'

const OutlinedPaths = () => (
  <>
    <path d="M2 12.75H7.91991C8.23049 12.75 8.52343 12.8943 8.71272 13.1405L9.64978 14.3595C9.83907 14.6057 10.132 14.75 10.4426 14.75H13.5574C13.868 14.75 14.1609 14.6057 14.3502 14.3595L15.2873 13.1405C15.4766 12.8943 15.7695 12.75 16.0801 12.75H22M22.1399 12.5352L18.4288 5.29391C18.2576 4.96001 17.914 4.75 17.5388 4.75H6.46118C6.08599 4.75 5.74237 4.96001 5.57125 5.29391L1.86007 12.5352C1.78773 12.6764 1.75 12.8327 1.75 12.9913V18.25C1.75 18.8023 2.19772 19.25 2.75 19.25H21.25C21.8023 19.25 22.25 18.8023 22.25 18.25V12.9913C22.25 12.8327 22.2123 12.6764 22.1399 12.5352Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
  </>
)

const FilledPaths = () => (
  <>
    <path fillRule="evenodd" clipRule="evenodd" d="M4.9038 4.95184C5.20326 4.36753 5.8046 4 6.46118 4H17.5388C18.1954 4 18.7967 4.36752 19.0962 4.95184L22.8074 12.1932C22.934 12.4402 23 12.7138 23 12.9913V18.25C23 19.2165 22.2165 20 21.25 20H2.75C1.7835 20 1 19.2165 1 18.25V12.9913C1 12.7138 1.06602 12.4402 1.19262 12.1932L4.9038 4.95184ZM21.5 13.5H16.0801C16.0024 13.5 15.9292 13.5361 15.8819 13.5976L14.9448 14.8166C14.6136 15.2475 14.1009 15.5 13.5574 15.5H10.4426C9.89908 15.5 9.38643 15.2475 9.05517 14.8166L8.11811 13.5976C8.07079 13.5361 7.99755 13.5 7.91991 13.5H2.5V18.25C2.5 18.3881 2.61193 18.5 2.75 18.5H21.25C21.3881 18.5 21.5 18.3881 21.5 18.25V13.5Z" fill="currentColor" />
  </>
)

const pathsByFill = {
  [IconFill.Outlined]: OutlinedPaths,
  [IconFill.Filled]: FilledPaths,
}

export const IconInboxEmpty = memo(function IconInboxEmpty({
  size = IconSize.Medium,
  fill = IconFill.Outlined,
  title,
  className,
  ref,
  ...props
}: IconWithFillProps) {
  const Paths = pathsByFill[fill]
  const px = iconSizeValues[size]

  return (
    <svg
      width={px}
      height={px}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      className={cn('shrink-0', className)}
      ref={ref}
      {...props}
    >
      <Paths />
    </svg>
  )
})
