/**
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-icons
 * Source: @central-icons-react
 *
 * @generated
 */

import { memo } from 'react'

import { cn } from '#lib/cn'

import { type IconProps, IconSize, iconSizeValues } from '../types'

export const IconChevronGrabberVertical = memo(function IconChevronGrabberVertical({
  size = IconSize.Medium,
  title,
  className,
  ref,
  ...props
}: IconProps) {
  const px = iconSizeValues[size]

  return (
    <svg
      width={px}
      height={px}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      className={cn('shrink-0', className)}
      ref={ref}
      {...props}
    >
      <path d="M8 8.99989L11.4697 5.53022C11.7626 5.23732 12.2374 5.23732 12.5303 5.53022L16 8.99989" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M16 15L12.5303 18.4697C12.2374 18.7626 11.7626 18.7626 11.4697 18.4697L8 15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
})
